# Generated by Django 4.1.5 on 2023-02-03 09:59

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashbords',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image_path, verbose_name='تصویر')),
                ('u_name', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('f_name', models.CharField(max_length=50, verbose_name='نام')),
                ('l_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('ph_number', models.CharField(max_length=50, verbose_name='تلفن همراه')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
