# Generated by Django 4.1.5 on 2023-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_place_dashbord_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbord',
            name='f_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='dashbord',
            name='l_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='dashbord',
            name='ph_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن همراه'),
        ),
    ]
