# Generated by Django 4.1.5 on 2023-02-03 10:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dashbord_f_name_alter_dashbord_l_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashbord',
            name='image',
        ),
        migrations.AddField(
            model_name='dashbord',
            name='profile',
            field=models.ImageField(default='profiles/0.png', upload_to=accounts.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
