# Generated by Django 4.1.5 on 2023-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_incomingproduct_date'),
        ('accounts', '0005_remove_dashbord_image_dashbord_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashbord',
            name='liked',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='مورد علاقه ها'),
        ),
    ]
