# Generated by Django 4.1.5 on 2023-02-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
