# Generated by Django 4.1.5 on 2023-02-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_price_discount'),
        ('tags', '0002_remove_tag_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='محصولات'),
        ),
    ]
