# Generated by Django 4.1.5 on 2023-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='عنوان در url'),
        ),
    ]
