# Generated by Django 4.1.5 on 2023-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='عنوان در url'),
        ),
    ]
