# Generated by Django 4.1.5 on 2023-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook',
            field=models.CharField(default=0, max_length=50, verbose_name='تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_sentence',
            field=models.CharField(default=0, max_length=150, verbose_name='جمله اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(default=0, max_length=50, verbose_name='تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tweeter',
            field=models.CharField(default=0, max_length=50, verbose_name='تلفن'),
            preserve_default=False,
        ),
    ]
