# Generated by Django 4.1.5 on 2023-01-30 12:35

from django.db import migrations, models
import django.db.models.deletion
import dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0004_alter_sitesetting_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=dynamics.models.upload_image_path, verbose_name='تصویر')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamics.sitesetting')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
