# Generated by Django 4.1.5 on 2023-01-30 12:45

from django.db import migrations, models
import dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ref',
            field=models.CharField(default=0, max_length=150, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dynamics.models.upload_categoryimage_path, verbose_name='تصویر'),
        ),
    ]
