# Generated by Django 4.1.5 on 2023-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_incomingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingproduct',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
