# Generated by Django 4.1.5 on 2023-02-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_incomingproduct_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
