# Generated by Django 4.1.5 on 2023-02-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
