# Generated by Django 4.1.5 on 2023-02-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productcomment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='date',
        ),
    ]
