# Generated by Django 4.1.5 on 2023-02-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productcomment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
